bot_config:
  api_key: ""
  link: "t.me/roosterLunchBot"
  interval: 15 # интервал в минутах
  time_to_poll: "10:15" # время отправки опроса

poll_config:
  chat_id: -765099735 #число типа int64 уникально для каждого чата
  question: "Заказываешь обед?"
  end_poll_text: "Голосование завершено"
  type: "regular" # можно изпользовать "quiz", чтобы викторину делать
  options: ['Да', 'Нет', 'Закажу сам'] # можно добавлять варианты ответов
  is_anonymous: false # true - анонимное голосование, false - открытое
  сorrect_option_id: 0 # если выбран Quiz надо выбрать нужный вариант ответа
  allows_multiple_answers: false # если выбрать true
  open_period: # количество секунд, после прошествия которых, голосование заканчивается, 600 - максимально 0 - без ограничений
